### PR TITLE
Spaced between functions and blocks

### PR DESCRIPTION
**Pull request by elpete**
I propose functions should have a space between the declaration and the block.
1. It matches the popular formatting in JavaScript, which CFScript is designed to look like.
2. It is consistent with the rest of the spacing settings which are all `spaced` instead of `compact`.

### CODE REVIEW

**Comment by lmajano** [comment]
@elpete can you add an example of the output please

**Comment by elpete** [comment]
```
function tap( value, callback ) {
    callback( value );
    return value;
}

tap( entity, function() {
    writeDump( “here” );
} );
```

**Comment by bdw429s** [comment]
Again, I don't really care what JS does here.  For me it's spaces for the sake of spaces.  Spaces are there to separate words or important flow control parts of the code for readability.  So for example,
 ```js
if( foo ){
```
has a nice comfortable spacing that pulls out the condition from the start and end of the if(), but
 
```js
if ( foo ) {
```
is just too e x p a n d e d for no reason.  We don't need additional spaces in there for any real purpose any more than you'd need one "At the end of a quoted sentence! "  :point_left: That's incorrect grammar and for good reason.  The ending quote doesn't need any extra spacing to separate it from the exclamation point since there are no more words or otherwise important parts of the sentence.  Likewise, spaces in code are to separate important things, not to just add everywhere because we can or because some JS people do it.

That said, this is a matter of _single whitespace characters_ and therefore of rather low importance IMO that we need to have a mandate on it.  I would say so long as you "cushion" your condition so it's not

```js
if(foo){
```
that's enough for me.

**Comment by lmajano** [comment]
@elpete I think this can be an individual decision per repo. Let's leave the base one as is, but you can implement this whitespace approach in your repos.

**Comment by lmajano** [comment]
Oops, I actually meant to merge this one, oops, can you repo

**Comment by lmajano** [comment]
Sorry, I was commenting on the wrong one. I will merge this and individual repos can decide to implement or note, but this can be base.

**Pull request merged**
